apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tb8p2rrhk-java-springboot
  janus-idp.io/tekton: tb8p2rrhk-java-springboot
  backstage.io/kubernetes-id: tb8p2rrhk-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tb8p2rrhk-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
